### ISSUE TITLE
Quitting the app logs a user out

### ISSUE THREAD

**Issue by sammyd** [razeware/emitron-iOS#501]
This is with the version on TestFlight, on iOS 14. The version in the App Store does not have the same problem.

1. Get the version on test flight on an iOS 14 device
2. Open and log in
3. Force quit the app
4. Open it again

The user should still be logged in. They are not.

**Comment by VegetarianZombie** [comment]
Hi @sammyd - I've investigated the issue. It appears that a property wrapper didSet observer is not being called. This may be a regression introduced with iOS 14. I'm figuring out a workaround now.

**Comment by VegetarianZombie** [comment]
Okay, I have resolved this issue. I thought this was a regression in iOS but the issue was related to trying to set a value by way of a property wrapper before super.init(). The property wrapper calls the method fetchPermissionsIfNeeded() which isn't allowed before the super init. Yet, no compile errors are thrown. 

Instead, I moved the set call after super init and that appears to resolve the error. I tested on both the simulator and device and it works.
