### ISSUE TITLE
Settings: Move settings to it's own tab

### ISSUE THREAD

**Issue by luke-freeman** [razeware/emitron-iOS#528]
Settings currently lives under 'My Tutorials'. Move Settings to it's own top level tab

### Expected behavior

Settings has it's own tab

<img width="376" alt="Screenshot 2020-11-06 at 16 26 17" src="https://user-images.githubusercontent.com/5320361/98383741-288f9080-204d-11eb-99c4-941d631dee5b.png">

### Actual behavior

Settings can only be accessed from My Tutorials

<img width="373" alt="Screenshot 2020-11-06 at 16 29 14" src="https://user-images.githubusercontent.com/5320361/98383791-3a713380-204d-11eb-8575-9591bf88c8d5.png">

**Comment by byaruhaf** [comment]
@luke-freeman, I'm trying to implement this enhancement wanted your advice on three items 

1. Move Settings to it's own top level tab, does that mean that we remove Settings from My Tutorials
2. If 1 above is true then X in the setting screen is no longer needed since switching away from settings will done on the tab bar.
3. is there a Design for Settings with a tab bar the only one I see in Figma is setting with out a tab bar. 

|Image|GIF|
|:-------------------------:|:-------------------------
|![IMG_9EB8E67C67C1-1](https://user-images.githubusercontent.com/4116539/98868483-ddc0af00-2478-11eb-96ec-818eb7f594f1.jpeg)  |  ![RPReplay_Final1605123387](https://user-images.githubusercontent.com/4116539/98868467-d6010a80-2478-11eb-95bb-65e7a38e0b29.gif) |

**Comment by luke-freeman** [comment]
@byaruhaf 

- That's right it should no longer exist on 'My Tutorials'
- There's no design but can you set it up as if it wasn't a modal and instead a typical view? (So no x)

**Comment by luke-freeman** [comment]
@byaruhaf @0xTim 

Functionally this works great!

But the new settings icon is misaligned. Can you align it to the top with the other icons?

<img width="723" alt="Screenshot 2020-12-17 at 10 13 41" src="https://user-images.githubusercontent.com/5320361/102467494-a41f2d00-4050-11eb-9bc3-8723501071f2.png">

**Comment by byaruhaf** [comment]
@luke-freeman I have updated the setting icon is this ok. 

![Simulator Screen Shot - iPhone 12 Pro Max - 2020-12-17 at 12 35 53](https://user-images.githubusercontent.com/4116539/102476999-780da700-4064-11eb-86a0-d6eaed34fbef.png)

**Comment by luke-freeman** [comment]
![Screenshot 2020-12-17 at 11 57 46](https://user-images.githubusercontent.com/5320361/102479419-2a427000-405f-11eb-8b3b-d3101323fa1a.png)

@byaruhaf 

Now the settings icon is too big. It should be the same size as the others and sit comfortably between the lines in the screenshot above

**Comment by byaruhaf** [comment]
@luke-freeman I have shrunk the icon, please check two options below:

**Option 1**
![23](https://user-images.githubusercontent.com/4116539/102506793-29740300-408c-11eb-81e0-f89dd08f35fb.png)

**Option 2**
![21](https://user-images.githubusercontent.com/4116539/102506804-2da02080-408c-11eb-978d-926f93b61ac2.png)

**Comment by luke-freeman** [comment]
@byaruhaf 

I think the settings icon needs to be 1-2pt/px bigger. 

Also I see some new issues: 

- Is it just me or the settings icon appears blurry now?
- Also the settings icon is using a different grey to the other icons

**Comment by bladebunny** [comment]
PR submitted to match existing icons.
https://github.com/razeware/emitron-iOS/pull/559

**Comment by byaruhaf** [comment]
Hi @luke-freeman 

Have you taken a look at the settings icons in PR  #561? They look as shown below:
if this is ok then we can close this issue.
if it's not ok can you design the setting icon the same as the library icon & library icon for this use case

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-07 at 04 43 54](https://user-images.githubusercontent.com/4116539/113798637-3d876180-975c-11eb-8f0d-9355409f2867.png)

**Comment by bladebunny** [comment]
For some reason this isn't the most recent.  Here's what at least the PR for the settings icon itself looks like.  (Lines added in Dark Mode).  I can switch out the image if need be.  The issue was the first set of icons use actual images whereas the settings icon was using a font image (systemName) -- where the final size and internal padding vary.  I would argue where precision counts you probably don't want to use the system font images.  I would prefer svg images or png's.

![Simulator Screen Shot - iPhone 12 Pro - 2021-04-07 at 12 02 19](https://user-images.githubusercontent.com/1473399/113920903-3f701580-979a-11eb-970d-dfe9dac33615.png)
![Simulator Screen Shot - iPhone 12 Pro - 2021-04-07 at 12 02 40](https://user-images.githubusercontent.com/1473399/113920913-439c3300-979a-11eb-9e67-a6683d235602.png)

**Comment by byaruhaf** [comment]
This looks good, lets wait for @luke-freeman comment

**Comment by luke-freeman** [comment]
@byaruhaf @bladebunny 

Looks excellent thanks!
